hw2: css-styles
ok-technopolis-autumn-2019/Vladislav_Zybkin pull request #2
Opened 2019-10-15 10:15 UTC by zvladn7

2019-10-15 11:01 UTC, fromanywhere requested changes

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +  align-content: center;
Кажется, это лишнее

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +.todo-app section {
лучше использовать селекторы по классам

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +  flex-grow: 1;
а зачем? Я бы просто явно размер задал

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +  flex-grow: 10;
тогда здесь flex-grow: 1

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +  width: 562px;
лучше не «распирать» элементом приложение, а задавать размер снаружи, чтобы содержимое растягивалось. Так управлять геометрией будет проще

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +  min-height: 30px;
а в чем идея?

2019-10-15 11:01 UTC, fromanywhere commented on index.html
> +                <label class="input-assignment" for="JS-checkbox">
Теперь клик в текст выбирает чекбокс, это не то, что ожидается

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +  width: 40px;
Если бы не редактирование, было бы красивое решение, хотя и не вполне атомарное, но, к сожалению, у нас так не получится

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +  flex-grow: 20;
когда тут такие числа, значит, что-то где-то пошло не так

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +  border: 2px solid #E6E6E6;
прыгает по горизонтали на клик между пунктами

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +  display: none;
Здесь умер фокус

2019-10-15 11:01 UTC, fromanywhere commented on main.css
> +
Неплохое начало, нужно больше внимания на ux — больше активная область у поля ввода, фокусы

2019-10-22 13:45 UTC, zvladn7 commented on main.css
> +  align-content: center;
Убрал.

2019-10-22 13:47 UTC, zvladn7 commented on main.css
> +  flex-grow: 1;
исправил, тк задание по размеру позволяет приблизиться к макету.

2019-10-22 13:47 UTC, zvladn7 commented on main.css
> +  flex-grow: 10;
Задал размеры явно

2019-10-22 13:48 UTC, zvladn7 commented on main.css
> +  width: 562px;
упустил этот момент. Теперь задаю размер снаружи

2019-10-22 13:49 UTC, zvladn7 commented on main.css
> +  min-height: 30px;
а это я экспериментировал и забыл убрать)

2019-10-22 13:49 UTC, zvladn7 commented on index.html
> +                <label class="input-assignment" for="JS-checkbox">
Вернулся к исходному варианту.

2019-10-22 13:50 UTC, zvladn7 commented on main.css
> +  width: 40px;
поменял замену checkbox'ов в соответствии с тем, что вы говорили на последней лекции

2019-10-22 13:51 UTC, zvladn7 commented on main.css
> +  display: none;
поправил фокусы

2019-10-22 13:54 UTC, zvladn7 commented on main.css
> +  display: none;
Вот только вопрос про фокусы на radio. Это нормально, что фокус идет только на выбранную мною позицию?

2019-10-22 15:49 UTC, fromanywhere commented on main.css
> +  display: none;
да, там дальше стрелками влево-вправо

2019-10-22 16:06 UTC, fromanywhere requested changes

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +.todo-app__header h1 {
у нас теперь БЭМ, селекторы по тегам там не принимаются

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  letter-spacing: -2.5px;
font-weight: 70; не бывает, бывает 100; line-height лучше коэффициентом, например, 1.2,, отступы тогда потюнить marginами. Letter-spacing не нужно отрицательным делать

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  width: 32px;
переписали значение из 69 строки, зачем? Из-за marginов площадь элемента теперь мелкая

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  width: 30px;
Вот эта кнопка должна быть прям по всей высоте верхнего бара

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  background-image: url(images/select-all.png);
Здесь нужно учесть дисплеи повышенной четкости и либо подгружать картинку @2x через media query, либо использовать svg

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  border: 1px solid silver;
А вот если использовать border-bottom, будет ближе к макету. А если еще и цвет из макета взять, вообще будет удачно

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  background-color: lightgray;
цвет из макета, сейчас вообще иконка удаления почти сливается

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +.assignment-item__current-view: hover .assignment-item__status:not(:checked) + .assignment-item__status-icon {
мне кажется, здесь пробел перед hover может не работать

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  height: 64px;
из-за явно заданной высоты возникают проблемы при большом количестве текста

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  margin-top: 0px;
тут бы еще :focus, с клавиатуры теряется

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +.assignment-item__current-view .assignment-item__delete-button {
вроде бы каскад не нужен

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  vertical-align: center;
это свойство не сработает здесь, но вроде бы и так всё хорошо

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  position: relative;
Если бы гарнитура задавалась здесь (а еще лучше на body), то в футере не потерялись бы шрифты

2019-10-22 16:06 UTC, fromanywhere commented on main.css
> +  padding: 0;
нужно проследить, чтобы шрифт на кнопке был такой же, как везде рядом в футере. Вообще везде хотелось бы поближе к макету, хотя бы по цветам и по отступам

2019-10-23 20:57 UTC, zvladn7 commented
@fromanywhere исправил все замечания.

2019-10-24 16:12 UTC, fromanywhere requested changes
Последний рывок — правите мелочи, получаете апрув

2019-10-24 16:12 UTC, fromanywhere commented on main.css
> +  width: 562px;
если здесь убрать ширину и добавить белый фон, уйдут проблемы с тенями

2019-10-24 16:12 UTC, fromanywhere commented on main.css
> +  vertical-align: center;
Так и осталось невалидным

2019-10-24 16:12 UTC, fromanywhere commented on main.css
> +  width: 562px;
ширина не нужна, высота тоже

2019-10-24 16:12 UTC, fromanywhere commented on main.css
> +  width: 500px;
Она же ниже переопределяется, зачем

2019-10-24 16:12 UTC, fromanywhere commented on main.css
> +  width: 500px;
из-за того, что здесь фиксированная ширина, всё рвется на узком дисплее. Возьмите flex-grow: 1;

2019-10-24 16:12 UTC, fromanywhere commented on main.css
> +  width: 99%
я бы здесь написал вместо этого
    width: 100%;
    box-sizing: border-box;
    border: 1px transparent solid;

и тогда уйдут прыжки на фокус

2019-10-24 16:40 UTC, zvladn7 commented
@fromanywhere готово.

2019-10-24 16:51 UTC, fromanywhere approved these changes

2019-10-24 16:52 UTC, merged